apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      containers:
      - name: bookapi
        image: deninpaul/bookapi
        resources:
          limits:
            memory: "356Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookapi-service
spec:
  type: LoadBalancer
  selector:
    app: bookapi
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP